services:
  tailscale:
    cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_ADMIN"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"
    command:
      - "/usr/local/bin/containerboot"
    container_name: "tailscale"
    environment:
      - "TS_ROUTES=192.168.1.0/24"
      - "TS_EXTRA_ARGS="
    env_file:
      - ./volume1/docker/secrets/tailscale.env
    hostname: "bm-tailscale"
    image: "tailscale/tailscale:latest"
    ipc: "private"
    logging:
      driver: "json-file"
      options: {}
    network_mode: "host"
    restart: "unless-stopped"
    volumes:
      - "/dev/net/tun:/dev/net/tun"
      - "/volume1/docker/tailscale:/var/lib"

version: "3.6"
volumes:
  portainer_data:
    external: true